#include <vulkan/vulkan.h>
#include <glm/glm.hpp>
#include <vector>
#include <fstream>
#include <iostream>
#include <cstring>
#include <stdexcept>
#include <cassert>
#include <functional>
using glm::vec3;using glm::vec4;using glm::mat4;
#define CHECK(call) do{VkResult r=(call);if(r!=VK_SUCCESS)throw std::runtime_error(#call+std::string(" result ")+std::to_string(r));}while(0)
constexpr uint32_t W=64,H=64;
VkInstance inst;VkPhysicalDevice physical;VkDevice device;VkQueue queue;VkCommandPool pool;
VkPhysicalDeviceMemoryProperties memProps;int validationErrors=0;
PFN_vkCreateAccelerationStructureKHR createAS;PFN_vkDestroyAccelerationStructureKHR destroyAS;
PFN_vkGetAccelerationStructureBuildSizesKHR getSizes;PFN_vkGetAccelerationStructureDeviceAddressKHR asAddress;PFN_vkCmdBuildAccelerationStructuresKHR buildAS;
VKAPI_ATTR VkBool32 VKAPI_CALL debugFn(VkDebugUtilsMessageSeverityFlagBitsEXT sev,VkDebugUtilsMessageTypeFlagsEXT,const VkDebugUtilsMessengerCallbackDataEXT*data,void*){if(sev&VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT){validationErrors++;std::cerr<<"VALIDATION ERROR: "<<data->pMessage<<"\n";}return VK_FALSE;}
uint32_t memoryType(uint32_t bits,VkMemoryPropertyFlags flags){for(uint32_t i=0;i<memProps.memoryTypeCount;i++)if((bits&(1<<i))&&(memProps.memoryTypes[i].propertyFlags&flags)==flags)return i;throw std::runtime_error("memory type");}
struct Buffer{VkBuffer buf{};VkDeviceMemory mem{};VkDeviceSize size{};void*ptr{};VkDeviceAddress addr{};};
std::vector<Buffer> buffers;
Buffer buffer(VkDeviceSize n,VkBufferUsageFlags usage){Buffer b;b.size=n;VkBufferCreateInfo ci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};ci.size=n;ci.usage=usage;ci.sharingMode=VK_SHARING_MODE_EXCLUSIVE;CHECK(vkCreateBuffer(device,&ci,nullptr,&b.buf));VkMemoryRequirements req;vkGetBufferMemoryRequirements(device,b.buf,&req);VkMemoryAllocateFlagsInfo flags{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO};flags.flags=VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);if(usage&VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT)ai.pNext=&flags;CHECK(vkAllocateMemory(device,&ai,nullptr,&b.mem));CHECK(vkBindBufferMemory(device,b.buf,b.mem,0));CHECK(vkMapMemory(device,b.mem,0,VK_WHOLE_SIZE,0,&b.ptr));if(usage&VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT){VkBufferDeviceAddressInfo di{VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO};di.buffer=b.buf;b.addr=vkGetBufferDeviceAddress(device,&di);}buffers.push_back(b);return b;}
void submit(std::function<void(VkCommandBuffer)> record){VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ai.commandPool=pool;ai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ai.commandBufferCount=1;VkCommandBuffer cmd;CHECK(vkAllocateCommandBuffers(device,&ai,&cmd));VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};bi.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;CHECK(vkBeginCommandBuffer(cmd,&bi));record(cmd);CHECK(vkEndCommandBuffer(cmd));VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&cmd;CHECK(vkQueueSubmit(queue,1,&si,VK_NULL_HANDLE));CHECK(vkQueueWaitIdle(queue));vkFreeCommandBuffers(device,pool,1,&cmd);}
void barrier(VkCommandBuffer cmd,VkPipelineStageFlags from,VkPipelineStageFlags to,VkAccessFlags src,VkAccessFlags dst){VkMemoryBarrier mb{VK_STRUCTURE_TYPE_MEMORY_BARRIER};mb.srcAccessMask=src;mb.dstAccessMask=dst;vkCmdPipelineBarrier(cmd,from,to,0,1,&mb,0,nullptr,0,nullptr);}
std::vector<VkAccelerationStructureKHR> structures;
VkAccelerationStructureKHR acceleration(VkAccelerationStructureTypeKHR type,const VkAccelerationStructureGeometryKHR& geom,uint32_t count){VkAccelerationStructureBuildGeometryInfoKHR info{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR};info.type=type;info.flags=VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR;info.mode=VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR;info.geometryCount=1;info.pGeometries=&geom;VkAccelerationStructureBuildSizesInfoKHR sizes{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR};getSizes(device,VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR,&info,&count,&sizes);auto storage=buffer(sizes.accelerationStructureSize,VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT);auto scratch=buffer(sizes.buildScratchSize+256,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT);VkAccelerationStructureCreateInfoKHR ci{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_KHR};ci.buffer=storage.buf;ci.size=sizes.accelerationStructureSize;ci.type=type;VkAccelerationStructureKHR as;CHECK(createAS(device,&ci,nullptr,&as));structures.push_back(as);info.dstAccelerationStructure=as;info.scratchData.deviceAddress=(scratch.addr+255)&~VkDeviceAddress(255);VkAccelerationStructureBuildRangeInfoKHR range{};range.primitiveCount=count;const VkAccelerationStructureBuildRangeInfoKHR* ranges[]={&range};submit([&](VkCommandBuffer cmd){buildAS(cmd,1,&info,ranges);barrier(cmd,VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR,VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR);});return as;}
VkAccelerationStructureKHR scene(bool closed,float lo,float hi,bool crowded=false){std::vector<vec3> p;vec3 offset(0);auto tri=[&](vec3 a,vec3 b,vec3 c){p.insert(p.end(),{a+offset,b+offset,c+offset});};auto quad=[&](vec3 a,vec3 b,vec3 c,vec3 d){tri(a,b,c);tri(a,c,d);};const float r=16;vec3 offsets[]={vec3(32,0,0),vec3(0,32,0),vec3(-32,0,0),vec3(0,-32,0),vec3(0)};for(int ci=0;ci<(crowded?5:1);ci++){offset=crowded?offsets[ci]:vec3(0);quad({-r,-r,lo},{r,-r,lo},{r,-r,hi},{-r,-r,hi});quad({r,-r,lo},{r,r,lo},{r,r,hi},{r,-r,hi});quad({r,r,lo},{-r,r,lo},{-r,r,hi},{r,r,hi});quad({-r,r,lo},{-r,-r,lo},{-r,-r,hi},{-r,r,hi});if(closed){quad({-r,-r,lo},{-r,r,lo},{r,r,lo},{r,-r,lo});quad({-r,-r,hi},{r,-r,hi},{r,r,hi},{-r,r,hi});}}auto vertices=buffer(p.size()*sizeof(vec3),VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT);memcpy(vertices.ptr,p.data(),p.size()*sizeof(vec3));VkAccelerationStructureGeometryKHR g{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR};g.geometryType=VK_GEOMETRY_TYPE_TRIANGLES_KHR;g.flags=VK_GEOMETRY_OPAQUE_BIT_KHR;auto&t=g.geometry.triangles;t.sType=VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_TRIANGLES_DATA_KHR;t.vertexFormat=VK_FORMAT_R32G32B32_SFLOAT;t.vertexData.deviceAddress=vertices.addr;t.vertexStride=sizeof(vec3);t.maxVertex=p.size()-1;t.indexType=VK_INDEX_TYPE_NONE_KHR;auto blas=acceleration(VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR,g,p.size()/3);VkAccelerationStructureDeviceAddressInfoKHR da{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_DEVICE_ADDRESS_INFO_KHR};da.accelerationStructure=blas;VkAccelerationStructureInstanceKHR instance{};instance.transform.matrix[0][0]=instance.transform.matrix[1][1]=instance.transform.matrix[2][2]=1;instance.mask=2;instance.flags=VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;instance.accelerationStructureReference=asAddress(device,&da);auto instances=buffer(sizeof(instance),VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT);memcpy(instances.ptr,&instance,sizeof(instance));g={VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR};g.geometryType=VK_GEOMETRY_TYPE_INSTANCES_KHR;g.geometry.instances.sType=VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_INSTANCES_DATA_KHR;g.geometry.instances.data.deviceAddress=instances.addr;return acceleration(VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR,g,1);}
struct Uniform {mat4 invViewProj;vec4 eye,depthInfo,params,gridOrigin,gridInvSize,gridBounds,soft,actorInfo;vec4 actors[64],actorLight[64],actorRange[64],actorRest;};
int main(int argc,char**argv){try{
 VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="QuakeLive shadow validation";app.apiVersion=VK_API_VERSION_1_2;
 const char*layer="VK_LAYER_KHRONOS_validation";const char*ext=VK_EXT_DEBUG_UTILS_EXTENSION_NAME;VkDebugUtilsMessengerCreateInfoEXT dbg{VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT};dbg.messageSeverity=VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT;dbg.messageType=VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT;dbg.pfnUserCallback=debugFn;
 VkInstanceCreateInfo ici{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ici.pApplicationInfo=&app;ici.enabledLayerCount=1;ici.ppEnabledLayerNames=&layer;ici.enabledExtensionCount=1;ici.ppEnabledExtensionNames=&ext;ici.pNext=&dbg;CHECK(vkCreateInstance(&ici,nullptr,&inst));VkDebugUtilsMessengerEXT messenger;auto createDebug=(PFN_vkCreateDebugUtilsMessengerEXT)vkGetInstanceProcAddr(inst,"vkCreateDebugUtilsMessengerEXT");CHECK(createDebug(inst,&dbg,nullptr,&messenger));uint32_t n=1;CHECK(vkEnumeratePhysicalDevices(inst,&n,&physical));vkGetPhysicalDeviceMemoryProperties(physical,&memProps);VkPhysicalDeviceProperties props;vkGetPhysicalDeviceProperties(physical,&props);std::cout<<"Device: "<<props.deviceName<<"\n";
 uint32_t nq=0;vkGetPhysicalDeviceQueueFamilyProperties(physical,&nq,nullptr);std::vector<VkQueueFamilyProperties> qs(nq);vkGetPhysicalDeviceQueueFamilyProperties(physical,&nq,qs.data());uint32_t qf=0;while(!(qs[qf].queueFlags&VK_QUEUE_COMPUTE_BIT))qf++;
 float priority=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=qf;qi.queueCount=1;qi.pQueuePriorities=&priority;
 VkPhysicalDeviceVulkan12Features f12{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES};f12.bufferDeviceAddress=VK_TRUE;VkPhysicalDeviceAccelerationStructureFeaturesKHR fas{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ACCELERATION_STRUCTURE_FEATURES_KHR};fas.accelerationStructure=VK_TRUE;f12.pNext=&fas;VkPhysicalDeviceRayQueryFeaturesKHR frq{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAY_QUERY_FEATURES_KHR};frq.rayQuery=VK_TRUE;fas.pNext=&frq;
 const char*extensions[]={VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME,VK_KHR_RAY_QUERY_EXTENSION_NAME,VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME};VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dci.queueCreateInfoCount=1;dci.pQueueCreateInfos=&qi;dci.pNext=&f12;dci.enabledExtensionCount=3;dci.ppEnabledExtensionNames=extensions;CHECK(vkCreateDevice(physical,&dci,nullptr,&device));vkGetDeviceQueue(device,qf,0,&queue);
 createAS=(PFN_vkCreateAccelerationStructureKHR)vkGetDeviceProcAddr(device,"vkCreateAccelerationStructureKHR");destroyAS=(PFN_vkDestroyAccelerationStructureKHR)vkGetDeviceProcAddr(device,"vkDestroyAccelerationStructureKHR");getSizes=(PFN_vkGetAccelerationStructureBuildSizesKHR)vkGetDeviceProcAddr(device,"vkGetAccelerationStructureBuildSizesKHR");asAddress=(PFN_vkGetAccelerationStructureDeviceAddressKHR)vkGetDeviceProcAddr(device,"vkGetAccelerationStructureDeviceAddressKHR");buildAS=(PFN_vkCmdBuildAccelerationStructuresKHR)vkGetDeviceProcAddr(device,"vkCmdBuildAccelerationStructuresKHR");
 VkCommandPoolCreateInfo pci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pci.queueFamilyIndex=qf;CHECK(vkCreateCommandPool(device,&pci,nullptr,&pool));
 auto ub=buffer(sizeof(Uniform),VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT);auto grid=buffer((5*5*3*10+4)*4,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT);auto output=buffer(W*H*sizeof(vec4),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT);auto staging=buffer(W*H*4,VK_BUFFER_USAGE_TRANSFER_SRC_BIT);std::fill_n((float*)staging.ptr,W*H,0.5f);
 VkImage image;VkDeviceMemory imem;VkImageCreateInfo imci{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};imci.imageType=VK_IMAGE_TYPE_2D;imci.format=VK_FORMAT_R32_SFLOAT;imci.extent={W,H,1};imci.mipLevels=imci.arrayLayers=1;imci.samples=VK_SAMPLE_COUNT_1_BIT;imci.tiling=VK_IMAGE_TILING_OPTIMAL;imci.usage=VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT;CHECK(vkCreateImage(device,&imci,nullptr,&image));VkMemoryRequirements ir;vkGetImageMemoryRequirements(device,image,&ir);VkMemoryAllocateInfo mai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};mai.allocationSize=ir.size;mai.memoryTypeIndex=memoryType(ir.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);CHECK(vkAllocateMemory(device,&mai,nullptr,&imem));CHECK(vkBindImageMemory(device,image,imem,0));
 submit([&](VkCommandBuffer cmd){VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;b.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.image=image;b.srcQueueFamilyIndex=b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};b.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);VkBufferImageCopy copy{};copy.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};copy.imageExtent={W,H,1};vkCmdCopyBufferToImage(cmd,staging.buf,image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&copy);b.oldLayout=b.newLayout;b.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;b.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,0,nullptr,1,&b);});
 VkImageView view;VkImageViewCreateInfo vci{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vci.image=image;vci.viewType=VK_IMAGE_VIEW_TYPE_2D;vci.format=imci.format;vci.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};CHECK(vkCreateImageView(device,&vci,nullptr,&view));VkSampler sampler;VkSamplerCreateInfo sci{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};sci.magFilter=sci.minFilter=VK_FILTER_NEAREST;sci.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST;sci.addressModeU=sci.addressModeV=sci.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;CHECK(vkCreateSampler(device,&sci,nullptr,&sampler));
 VkDescriptorType types[]={VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER};VkDescriptorSetLayoutBinding bindings[5]{};for(int i=0;i<5;i++){bindings[i].binding=i;bindings[i].descriptorType=types[i];bindings[i].descriptorCount=1;bindings[i].stageFlags=VK_SHADER_STAGE_COMPUTE_BIT;}VkDescriptorSetLayout layout;VkDescriptorSetLayoutCreateInfo lci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};lci.bindingCount=5;lci.pBindings=bindings;CHECK(vkCreateDescriptorSetLayout(device,&lci,nullptr,&layout));VkPipelineLayout playout;VkPipelineLayoutCreateInfo plci{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};plci.setLayoutCount=1;plci.pSetLayouts=&layout;CHECK(vkCreatePipelineLayout(device,&plci,nullptr,&playout));
 std::ifstream sf(argc>1?argv[1]:"actorshadow-test.spv",std::ios::binary|std::ios::ate);if(!sf)throw std::runtime_error("SPIR-V file");size_t sz=sf.tellg();sf.seekg(0);std::vector<uint32_t> code(sz/4);sf.read((char*)code.data(),sz);VkShaderModule module;VkShaderModuleCreateInfo mci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};mci.codeSize=sz;mci.pCode=code.data();CHECK(vkCreateShaderModule(device,&mci,nullptr,&module));VkComputePipelineCreateInfo cpci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};cpci.stage.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;cpci.stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;cpci.stage.module=module;cpci.stage.pName="main";cpci.layout=playout;VkPipeline pipeline;CHECK(vkCreateComputePipelines(device,VK_NULL_HANDLE,1,&cpci,nullptr,&pipeline));
 VkDescriptorPoolSize ps[]={{types[0],1},{types[1],1},{types[2],1},{types[3],2}};VkDescriptorPool dp;VkDescriptorPoolCreateInfo dpci{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpci.maxSets=1;dpci.poolSizeCount=4;dpci.pPoolSizes=ps;CHECK(vkCreateDescriptorPool(device,&dpci,nullptr,&dp));VkDescriptorSet set;VkDescriptorSetAllocateInfo dsai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};dsai.descriptorPool=dp;dsai.descriptorSetCount=1;dsai.pSetLayouts=&layout;CHECK(vkAllocateDescriptorSets(device,&dsai,&set));VkDescriptorImageInfo ii{sampler,view,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};VkDescriptorBufferInfo binfo[]={{ub.buf,0,ub.size},{grid.buf,0,grid.size},{output.buf,0,output.size}};VkWriteDescriptorSet writes[5]{};for(int i=0;i<5;i++){writes[i].sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;writes[i].dstSet=set;writes[i].dstBinding=i;writes[i].descriptorCount=1;writes[i].descriptorType=types[i];}writes[0].pImageInfo=&ii;writes[2].pBufferInfo=&binfo[0];writes[3].pBufferInfo=&binfo[1];writes[4].pBufferInfo=&binfo[2];
 Uniform u{};u.invViewProj=mat4(1);u.invViewProj[0][0]=u.invViewProj[1][1]=128;u.invViewProj[3][2]=-0.5;u.eye=vec4(0,0,256,0);u.depthInfo=vec4(0,0.9,1,0);u.params=vec4(1,512,2,1);u.gridOrigin=vec4(-128,-128,0,1);u.gridInvSize=vec4(1.f/64,1.f/64,1.f/64,0);u.gridBounds=vec4(5,5,3,1);u.soft=vec4(0,1,0,0);u.actorInfo=vec4(1,682,1,0);u.actors[0]=vec4(0,0,48,28);u.actorLight[0]=vec4(0,0,1,1);u.actorRange[0]=vec4(0,12,0,0);u.actorRest=vec4(12,1,0,0);
 auto gridSetup=[&](bool down,vec3 light){uint32_t*data=(uint32_t*)grid.ptr;memset(data,0,grid.size);for(int i=0;i<75;i++){data[i*2]=35u|(35u<<8)|(35u<<16)|(180u<<24);data[i*2+1]=180u|(180u<<8)|((down?128u:0u)<<16);float*field=(float*)(data+150+i*8);field[0]=light.x;field[1]=light.y;field[2]=light.z;field[3]=field[6]=field[7]=1;}};
 auto run=[&](const char*name,VkAccelerationStructureKHR top){memcpy(ub.ptr,&u,sizeof(u));memset(output.ptr,0,output.size);VkWriteDescriptorSetAccelerationStructureKHR wa{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_KHR};wa.accelerationStructureCount=1;wa.pAccelerationStructures=&top;writes[1].pNext=&wa;vkUpdateDescriptorSets(device,5,writes,0,nullptr);submit([&](VkCommandBuffer cmd){vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline);vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,playout,0,1,&set,0,nullptr);vkCmdDispatch(cmd,W/8,H/8,1);barrier(cmd,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_HOST_BIT,VK_ACCESS_SHADER_WRITE_BIT,VK_ACCESS_HOST_READ_BIT);});auto pixels=(vec4*)output.ptr;int shadowed=0;for(uint32_t i=0;i<W*H;i++)shadowed+=pixels[i].g<0.9;float center=pixels[(H/2)*W+W/2].g;std::ofstream raw(std::string(name)+".rgba32f",std::ios::binary);raw.write((char*)output.ptr,output.size);std::cout<<name<<": shadowed_pixels="<<shadowed<<", center_green="<<center<<"\n";return std::pair<int,float>(shadowed,center);};
 auto closed=scene(true,32,64);gridSetup(false,{0,0,128});auto a=run("closed_cube_up_grid",closed);assert(a.first>0&&a.second<0.9);
 gridSetup(true,{0,0,128});auto b=run("closed_cube_down_grid",closed);assert(b.first==a.first&&b.second==a.second);
 u.soft.z=1;auto gate=run("down_grid_sun_enabled",closed);assert(gate.first>0);u.params.w=0;auto weight=run("down_grid_normal_weight",closed);assert(weight.second>=0&&weight.second<=1);u.params.w=1;u.soft.z=0;
 gridSetup(false,{0,0,128});u.actorRange[0].y=8;auto open=scene(false,32,64);auto c=run("open_tube_up_grid",open);assert(c.first==0&&c.second==1);
 // A real lamp at z=100 must not be shadowed by a cube wholly beyond it.
 u.actorRange[0].y=12;auto beyond=scene(true,120,136);u.actorInfo.z=0;u.actors[0]=vec4(0,0,128,28);gridSetup(false,{0,0,100});auto d=run("caster_beyond_point_light",beyond);assert(d.first>0&&d.second<0.9);
 u.actorInfo.z=1;auto e=run("caster_beyond_light_E211_on",beyond);assert(e.first>0&&e.second<0.9);u.actorInfo.z=2;auto f=run("near_point_light_directional_fallback",beyond);assert(f.first>0);gridSetup(false,{0,0,64});auto clear=run("caster_beyond_clear_point_light_mode2",beyond);assert(clear.first==0);

 u.actorInfo.z=1;u.actorInfo.x=5;gridSetup(false,{0,0,128});auto crowded=scene(true,32,64,true);
 vec3 centers[]={vec3(32,0,48),vec3(0,32,48),vec3(-32,0,48),vec3(0,-32,48),vec3(0,0,48)};
 for(int k=0;k<5;k++){u.actors[k]=vec4(centers[k],28);u.actorLight[k]=vec4(0,0,1,1);u.actorRange[k]=vec4(k*12,(k+1)*12,0,0);}
 auto rank=run("fifth_caster_best_aligned",crowded);assert(rank.second<0.9);
 // Empty ranges represent whole casters skipped by the capacity preflight.
 for(int k=0;k<4;k++){u.actors[k]=vec4(0,0,48,28);u.actorRange[k]=vec4(0);}
 u.actorRange[4]=vec4(0,12,0,0);auto dropped=run("four_dropped_casters_before_real_caster",closed);
 assert(dropped.first==64 && dropped.second<0.9);std::cout<<"Dropped-caster budget regression present: "<<(dropped.second==1)<<"\n";

 u.actorInfo.x=1;u.actorInfo.z=1;u.actors[0]=vec4(0,0,48,28);u.actorRange[0]=vec4(0,12,0,0);u.soft.z=1;
 gridSetup(false,{0,0,48});float* gridFloats=(float*)grid.ptr;gridFloats[750]=0;gridFloats[751]=0;gridFloats[752]=1;gridFloats[753]=180;
 for(int i=0;i<75;i++)gridFloats[150+i*8+4]=1;
 auto sunDir=run("sun_aligned_direction_mode",closed);u.actorInfo.z=2;auto sunFallback=run("sun_aligned_point_fallback_mode",closed);
 auto px=(vec4*)output.ptr;assert(px[(H/2)*W+W/2].r==1);std::cout<<"Point-fallback center red channel="<<px[(H/2)*W+W/2].r<<" (0.25 means additional sun shadow)\n";
 CHECK(vkDeviceWaitIdle(device));vkDestroyDescriptorPool(device,dp,nullptr);vkDestroyPipeline(device,pipeline,nullptr);vkDestroyShaderModule(device,module,nullptr);vkDestroyPipelineLayout(device,playout,nullptr);vkDestroyDescriptorSetLayout(device,layout,nullptr);vkDestroySampler(device,sampler,nullptr);vkDestroyImageView(device,view,nullptr);vkDestroyImage(device,image,nullptr);vkFreeMemory(device,imem,nullptr);for(auto as:structures)destroyAS(device,as,nullptr);for(auto b:buffers){vkUnmapMemory(device,b.mem);vkDestroyBuffer(device,b.buf,nullptr);vkFreeMemory(device,b.mem,nullptr);}vkDestroyCommandPool(device,pool,nullptr);vkDestroyDevice(device,nullptr);auto destroyDebug=(PFN_vkDestroyDebugUtilsMessengerEXT)vkGetInstanceProcAddr(inst,"vkDestroyDebugUtilsMessengerEXT");destroyDebug(inst,messenger,nullptr);vkDestroyInstance(inst,nullptr);std::cout<<"Vulkan validation errors: "<<validationErrors<<"\n";return validationErrors?1:0;
 }catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
